### PR TITLE
Support for themes, monkeytype and graphs

### PR DESCRIPTION
**Pull request by robopuff**
This PR adds multiple improvements:
* New WPM graph (using [guptarohit/asciigraph](github.com/guptarohit/asciigraph))
  * Solves #3 
* New filter for minimum word length
* Added error on the empty list (can occur after min word length is used)
* Support for languages/dictionaries from [monkeytype](https://github.com/monkeytypegame/monkeytype) (read from GitHub repo)
  * More words and different dictionaries, including code-related, doesn't produce sentences
* Support for themes and overall ability to change colors of text, progress bar, and graph
  * I personally had an issue with default untyped text being unreadable, this fixes it and adds a bit of funk

Cheers :)

### CODE REVIEW

**Comment by maaslalani** [comment]
Whoaaaaa! This is some great stuff.
Thank you so much, I'm going to take a look soon.

**Comment by maaslalani** [comment]
This is so wonderful, I love it. Looks absolutely amazing!
image

**Comment by maaslalani** [comment]
Let me know if you want to be added as a collaborator on this repository, happy to do so! Thank you for the great work :)

**Comment by robopuff** [comment]
> Let me know if you want to be added as a collaborator on this repository, happy to do so! Thank you for the great work :)

Sorry for not replying sooner,
Yeah, would be nice to be added as a collaborator, cheers :)

**Comment by maaslalani** [comment]
@robopuff Cool, sent an invite! Thanks for all the amazing work :)

**Pull request merged**
