### PR TITLE
Read text from `stdin`

### PR DESCRIPTION
**Pull request by happyRip**
I added functionality to enable piping text into `typer` instead of having to rely on `babble` or an input file, as specified in #2 
typer

I also changed default `-c` and `-p` flags functionality to work more intuitively.
typer2

### CODE REVIEW

**Comment by maaslalani** [comment]
Thank you for the changes! I really appreciate the `stdin` functionality, it's awesome! (Maybe we should add some docs in the `README.md` about it).

For the flag changes, I'm not so sure the changes are intuitive, could you explain it to me? [monkeytype.com](https://monkeytype.com/) and [keybr.com](https://www.keybr.com/) both start off with all lowercase and no punctuation for their typing tests so I think `typer` should do the same. Then, if people want punctuation or capitalization they can opt-in.

**Comment by happyRip** [comment]
> For the flag changes, I'm not so sure the changes are intuitive, could you explain it to me?

Since we are using `stdin` now it seems strange to me that by just using `typer` without any flags input from `stdin` is stripped from any punctuation and swapped to lowercase, when it could be intended that way. I thought that input to the program should be consicered as user intended it to be.

**Comment by maaslalani** [comment]
> > For the flag changes, I'm not so sure the changes are intuitive, could you explain it to me?
> 
> Since we are using `stdin` now it seems strange to me that by just using `typer` without any flags input from `stdin` is stripped from any punctuation and swapped to lowercase, when it could be intended that way. I thought that input to the program should be considered as user intended it to be.

I think it's okay to filter the input in this case (for a typing test) since the user will probably use `stdin` to curl text from the web and `cat` files, etc... so it still makes sense for `typer` to use this input and remove punctuation and capitalization. If the user wants unchanged input then they can use the `-cp` flags. Currently it works this way for files as well with the `-f` flags. If users complain, then we can change this to your suggested solution, but I'd lean to keeping it as it currently is for now.

**Comment by happyRip** [comment]
Then the changes can be merged without  commit e351378

**Comment by maaslalani** [comment]
Merged in #15

**Pull request closed without merging**
